//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChristmasVillageGUI.Proxies
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:ChristmasVillageIFAC/FactoryTypeIFAC", ConfigurationName="ChristmasVillageGUI.Proxies.FactoryTypeIFAC")]
    public interface FactoryTypeIFAC
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ChristmasVillageIFAC/FactoryTypeIFAC/FactoryTypeIFAC/selectAll", ReplyAction="urn:ChristmasVillageIFAC/FactoryTypeIFAC/FactoryTypeIFAC/selectAllResponse")]
        System.Collections.Generic.List<ChristmasVillageBO.FactoryTypeBO> selectAll();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ChristmasVillageIFAC/FactoryTypeIFAC/FactoryTypeIFAC/selectAll", ReplyAction="urn:ChristmasVillageIFAC/FactoryTypeIFAC/FactoryTypeIFAC/selectAllResponse")]
        System.IAsyncResult BeginselectAll(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<ChristmasVillageBO.FactoryTypeBO> EndselectAll(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FactoryTypeIFACChannel : ChristmasVillageGUI.Proxies.FactoryTypeIFAC, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FactoryTypeIFACClient : System.ServiceModel.ClientBase<ChristmasVillageGUI.Proxies.FactoryTypeIFAC>, ChristmasVillageGUI.Proxies.FactoryTypeIFAC
    {
        
        public FactoryTypeIFACClient()
        {
        }
        
        public FactoryTypeIFACClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public FactoryTypeIFACClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public FactoryTypeIFACClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public FactoryTypeIFACClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<ChristmasVillageBO.FactoryTypeBO> selectAll()
        {
            return base.Channel.selectAll();
        }
        
        public System.IAsyncResult BeginselectAll(System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginselectAll(callback, asyncState);
        }
        
        public System.Collections.Generic.List<ChristmasVillageBO.FactoryTypeBO> EndselectAll(System.IAsyncResult result)
        {
            return base.Channel.EndselectAll(result);
        }
    }
}
