//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChristmasVillageGUI.Proxies
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:ChristmasVillageIFAC/ManageVillageIFAC", ConfigurationName="ChristmasVillageGUI.Proxies.ManageVillageIFAC")]
    public interface ManageVillageIFAC
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ChristmasVillageIFAC/ManageVillageIFAC/ManageVillageIFAC/createManageVillage", ReplyAction="urn:ChristmasVillageIFAC/ManageVillageIFAC/ManageVillageIFAC/createManageVillageR" +
            "esponse")]
        void createManageVillage(ChristmasVillageBO.ManageVillageBO village);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ChristmasVillageIFAC/ManageVillageIFAC/ManageVillageIFAC/createManageVillage", ReplyAction="urn:ChristmasVillageIFAC/ManageVillageIFAC/ManageVillageIFAC/createManageVillageR" +
            "esponse")]
        System.IAsyncResult BegincreateManageVillage(ChristmasVillageBO.ManageVillageBO village, System.AsyncCallback callback, object asyncState);
        
        void EndcreateManageVillage(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ChristmasVillageIFAC/ManageVillageIFAC/ManageVillageIFAC/findVillageByUser", ReplyAction="urn:ChristmasVillageIFAC/ManageVillageIFAC/ManageVillageIFAC/findVillageByUserRes" +
            "ponse")]
        ChristmasVillageBO.ManageVillageBO findVillageByUser(int id_User);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ChristmasVillageIFAC/ManageVillageIFAC/ManageVillageIFAC/findVillageByUser", ReplyAction="urn:ChristmasVillageIFAC/ManageVillageIFAC/ManageVillageIFAC/findVillageByUserRes" +
            "ponse")]
        System.IAsyncResult BeginfindVillageByUser(int id_User, System.AsyncCallback callback, object asyncState);
        
        ChristmasVillageBO.ManageVillageBO EndfindVillageByUser(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ManageVillageIFACChannel : ChristmasVillageGUI.Proxies.ManageVillageIFAC, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ManageVillageIFACClient : System.ServiceModel.ClientBase<ChristmasVillageGUI.Proxies.ManageVillageIFAC>, ChristmasVillageGUI.Proxies.ManageVillageIFAC
    {
        
        public ManageVillageIFACClient()
        {
        }
        
        public ManageVillageIFACClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ManageVillageIFACClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ManageVillageIFACClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ManageVillageIFACClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void createManageVillage(ChristmasVillageBO.ManageVillageBO village)
        {
            base.Channel.createManageVillage(village);
        }
        
        public System.IAsyncResult BegincreateManageVillage(ChristmasVillageBO.ManageVillageBO village, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BegincreateManageVillage(village, callback, asyncState);
        }
        
        public void EndcreateManageVillage(System.IAsyncResult result)
        {
            base.Channel.EndcreateManageVillage(result);
        }
        
        public ChristmasVillageBO.ManageVillageBO findVillageByUser(int id_User)
        {
            return base.Channel.findVillageByUser(id_User);
        }
        
        public System.IAsyncResult BeginfindVillageByUser(int id_User, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginfindVillageByUser(id_User, callback, asyncState);
        }
        
        public ChristmasVillageBO.ManageVillageBO EndfindVillageByUser(System.IAsyncResult result)
        {
            return base.Channel.EndfindVillageByUser(result);
        }
    }
}
